### ISSUE TITLE
Proyecto integrador

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-de-gps-team-pc-box#2]
[INTEGRACIÓN AL PROYECTO PRINCIPAL “TIENDA VIRTUAL PC BOX.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-gps-team-pc-box/files/8608098/INTEGRACION.AL.PROYECTO.PRINCIPAL.TIENDA.VIRTUAL.PC.BOX.pdf)

**Comment by Anthony4523** [comment]
La práctica contiene toda la información requerida
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
